-- =============================================================================
-- Quorum — seed data
--
-- NOTE: This project deliberately does NOT seed fake human users.
--
-- An earlier version of this file inserted 3,000 synthetic accounts into
-- auth.users with real-sounding names, presented on the leaderboard as genuine
-- players. That is astroturfing — it misleads new users about how many real
-- people use the product, and is a trust (and potentially legal/consumer-
-- protection) risk.
--
-- Instead, the cold-start / "empty leaderboard" problem is solved honestly with
-- clearly-labeled AI opponents ("bots"). See migration:
--
--     migrations/0006_bot_players.sql
--
-- Those rows live in their own `bot_players` table, every name ends in "-Bot",
-- and the frontend marks them with a 🤖 badge — so no one is misled into
-- thinking they're competing against a person. It's also on-theme: Quorum is a
-- game about AI models. The bots' XP drifts slowly via `tick_bot_xp()` (run on
-- a daily cron) so the board feels alive but an engaged human can out-climb it.
--
-- Real daily cases come from the `generate-daily-case` Edge Function (plus a
-- seed case in migration 0002 so day one works before the cron fires).
-- =============================================================================
